const dataEn = [
  { letter: '`', onShift: '~', keyCode: 'Backquote' },
  { letter: '1', onShift: '!', keyCode: 'Digit1' },
  { letter: '2', onShift: '@', keyCode: 'Digit2' },
  { letter: '3', onShift: '#', keyCode: 'Digit3' },
  { letter: '4', onShift: '$', keyCode: 'Digit4' },
  { letter: '5', onShift: '%', keyCode: 'Digit5' },
  { letter: '6', onShift: '^', keyCode: 'Digit6' },
  { letter: '7', onShift: '&', keyCode: 'Digit7' },
  { letter: '8', onShift: '*', keyCode: 'Digit8' },
  { letter: '9', onShift: '(', keyCode: 'Digit9' },
  { letter: '0', onShift: ')', keyCode: 'Digit0' },
  { letter: '-', onShift: '_', keyCode: 'Minus' },
  { letter: '=', onShift: '+', keyCode: 'Equal' },
  { letter: 'Backspace', onShift: 'Backspace', keyCode: 'Backspace' },
  { letter: 'Tab', onShift: 'Tab', keyCode: 'Tab' },
  { letter: 'q', onShift: 'Q', keyCode: 'KeyQ' },
  { letter: 'w', onShift: 'W', keyCode: 'KeyW' },
  { letter: 'e', onShift: 'E', keyCode: 'KeyE' },
  { letter: 'r', onShift: 'R', keyCode: 'KeyR' },
  { letter: 't', onShift: 'T', keyCode: 'KeyT' },
  { letter: 'y', onShift: 'Y', keyCode: 'KeyY' },
  { letter: 'u', onShift: 'U', keyCode: 'KeyU' },
  { letter: 'i', onShift: 'I', keyCode: 'KeyI' },
  { letter: 'o', onShift: 'O', keyCode: 'KeyO' },
  { letter: 'p', onShift: 'P', keyCode: 'KeyP' },
  { letter: '[', onShift: '{', keyCode: 'BracketLeft' },
  { letter: ']', onShift: '}', keyCode: 'BracketRight' },
  { letter: ' \\', onShift: '|', keyCode: 'Backslash' },
  { letter: 'Del', onShift: 'Del', keyCode: 'Delete' },
  { letter: 'CapsLock', onShift: 'CapsLock', keyCode: 'CapsLock' },
  { letter: 'a', onShift: 'A', keyCode: 'KeyA' },
  { letter: 's', onShift: 'S', keyCode: 'KeyS' },
  { letter: 'd', onShift: 'D', keyCode: 'KeyD' },
  { letter: 'f', onShift: 'F', keyCode: 'KeyF' },
  { letter: 'g', onShift: 'G', keyCode: 'KeyG' },
  { letter: 'h', onShift: 'H', keyCode: 'KeyH' },
  { letter: 'j', onShift: 'J', keyCode: 'KeyJ' },
  { letter: 'k', onShift: 'K', keyCode: 'KeyK' },
  { letter: 'l', onShift: 'L', keyCode: 'KeyL' },
  { letter: ';', onShift: ':', keyCode: 'Semicolon' },
  { letter: "'", onShift: '"', keyCode: 'Quote' },
  { letter: 'Enter', onShift: 'Enter', keyCode: 'Enter' },
  { letter: 'Shift', onShift: 'Shift', keyCode: 'ShiftLeft' },
  { letter: 'z', onShift: 'Z', keyCode: 'KeyZ' },
  { letter: 'x', onShift: 'X', keyCode: 'KeyX' },
  { letter: 'c', onShift: 'C', keyCode: 'KeyC' },
  { letter: 'v', onShift: 'V', keyCode: 'KeyV' },
  { letter: 'b', onShift: 'B', keyCode: 'KeyB' },
  { letter: 'n', onShift: 'N', keyCode: 'KeyN' },
  { letter: 'm', onShift: 'M', keyCode: 'KeyM' },
  { letter: ',', onShift: '<', keyCode: 'Comma' },
  { letter: '.', onShift: '>', keyCode: 'Period' },
  { letter: '/', onShift: '?', keyCode: 'Slash' },
  { letter: '↑', onShift: '↑', keyCode: 'ArrowUp' },
  { letter: 'Shift ', onShift: 'Shift', keyCode: 'ShiftRight' },
  { letter: 'Ctrl', onShift: 'Ctrl', keyCode: 'ControlLeft' },
  { letter: 'Win', onShift: 'Win', keyCode: 'MetaLeft' },
  { letter: 'Alt', onShift: 'Alt', keyCode: 'AltLeft' },
  { letter: '', onShift: '', keyCode: 'Space' },
  { letter: 'Alt', onShift: 'Alt', keyCode: 'AltRight' },
  { letter: '←', onShift: '←', keyCode: 'ArrowLeft' },
  { letter: '↓', onShift: '↓', keyCode: 'ArrowDown' },
  { letter: '→', onShift: '→', keyCode: 'ArrowRight' },
  { letter: 'Ctrl', onShift: 'Ctrl', keyCode: 'ControlRight' },
];

export default dataEn;
