const dataRu = [
  { letter: 'ё', keyCode: 'Backquote' },
  { letter: '1', keyCode: 'Digit1' },
  { letter: '2', keyCode: 'Digit2' },
  { letter: '3', keyCode: 'Digit3' },
  { letter: '4', keyCode: 'Digit4' },
  { letter: '5', keyCode: 'Digit5' },
  { letter: '6', keyCode: 'Digit6' },
  { letter: '7', keyCode: 'Digit7' },
  { letter: '8', keyCode: 'Digit8' },
  { letter: '9', keyCode: 'Digit9' },
  { letter: '0', keyCode: 'Digit0' },
  { letter: '-', keyCode: 'Minus' },
  { letter: '=', keyCode: 'Equal' },
  { letter: 'Backspace', keyCode: 'Backspace' },
  { letter: 'Tab', keyCode: 'Tab' },
  { letter: 'й', keyCode: 'KeyQ' },
  { letter: 'ц', keyCode: 'KeyW' },
  { letter: 'у', keyCode: 'KeyE' },
  { letter: 'к', keyCode: 'KeyR' },
  { letter: 'е', keyCode: 'KeyT' },
  { letter: 'н', keyCode: 'KeyY' },
  { letter: 'г', keyCode: 'KeyU' },
  { letter: 'ш', keyCode: 'KeyI' },
  { letter: 'щ', keyCode: 'KeyO' },
  { letter: 'з', keyCode: 'KeyP' },
  { letter: 'х', keyCode: 'BracketLeft' },
  { letter: 'ъ', keyCode: 'BracketRight' },
  { letter: ' \\', keyCode: 'Backslash' },
  { letter: 'Del', keyCode: 'Delete' },
  { letter: 'CapsLock', keyCode: 'CapsLock' },
  { letter: 'ф', keyCode: 'KeyA' },
  { letter: 'ы', keyCode: 'KeyS' },
  { letter: 'в', keyCode: 'KeyD' },
  { letter: 'а', keyCode: 'KeyF' },
  { letter: 'п', keyCode: 'KeyG' },
  { letter: 'р', keyCode: 'KeyH' },
  { letter: 'о', keyCode: 'KeyJ' },
  { letter: 'л', keyCode: 'KeyK' },
  { letter: 'д', keyCode: 'KeyL' },
  { letter: 'ж', keyCode: 'Semicolon' },
  { letter: "э", keyCode: 'Quote' },
  { letter: 'Enter', keyCode: 'Enter' },
  { letter: 'Shift', keyCode: 'ShiftLeft' },
  { letter: 'я', keyCode: 'KeyZ' },
  { letter: 'ч', keyCode: 'KeyX' },
  { letter: 'с', keyCode: 'KeyC' },
  { letter: 'м', keyCode: 'KeyV' },
  { letter: 'и', keyCode: 'KeyB' },
  { letter: 'т', keyCode: 'KeyN' },
  { letter: 'ь', keyCode: 'KeyM' },
  { letter: 'б', keyCode: 'Comma' },
  { letter: 'ю', keyCode: 'Period' },
  { letter: '/', keyCode: 'Slash' },
  { letter: '↑', keyCode: 'ArrowUp' },
  { letter: 'Shift ', keyCode: 'ShiftRight' },
  { letter: 'Ctrl', keyCode: 'ControlLeft' },
  { letter: 'Win', keyCode: 'MetaLeft' },
  { letter: 'Alt', keyCode: 'AltLeft' },
  { letter: '', keyCode: 'Space' },
  { letter: 'Alt', keyCode: 'AltRight' },
  { letter: '←', keyCode: 'ArrowLeft' },
  { letter: '↓', keyCode: 'ArrowDown' },
  { letter: '→', keyCode: 'ArrowRight' },
  { letter: 'Ctrl', keyCode: 'ControlRight' },
];

export default dataRu;