const dataRu = [
  { letter: 'ё', onShift: 'Ё', keyCode: 'Backquote' },
  { letter: '1', onShift: '!', keyCode: 'Digit1' },
  { letter: '2', onShift: '"', keyCode: 'Digit2' },
  { letter: '3', onShift: '№', keyCode: 'Digit3' },
  { letter: '4', onShift: ';', keyCode: 'Digit4' },
  { letter: '5', onShift: '%', keyCode: 'Digit5' },
  { letter: '6', onShift: ':', keyCode: 'Digit6' },
  { letter: '7', onShift: '?', keyCode: 'Digit7' },
  { letter: '8', onShift: '*', keyCode: 'Digit8' },
  { letter: '9', onShift: '(', keyCode: 'Digit9' },
  { letter: '0', onShift: ')', keyCode: 'Digit0' },
  { letter: '-', onShift: '_', keyCode: 'Minus' },
  { letter: '=', onShift: '+', keyCode: 'Equal' },
  { letter: 'Backspace', onShift: 'Backspace', keyCode: 'Backspace' },
  { letter: 'Tab', onShift: 'Tab', keyCode: 'Tab' },
  { letter: 'й', onShift: 'Й', keyCode: 'KeyQ' },
  { letter: 'ц', onShift: 'Ц', keyCode: 'KeyW' },
  { letter: 'у', onShift: 'У', keyCode: 'KeyE' },
  { letter: 'к', onShift: 'К', keyCode: 'KeyR' },
  { letter: 'е', onShift: 'Е', keyCode: 'KeyT' },
  { letter: 'н', onShift: 'Н', keyCode: 'KeyY' },
  { letter: 'г', onShift: 'Г', keyCode: 'KeyU' },
  { letter: 'ш', onShift: 'Ш', keyCode: 'KeyI' },
  { letter: 'щ', onShift: 'Щ', keyCode: 'KeyO' },
  { letter: 'з', onShift: 'З', keyCode: 'KeyP' },
  { letter: 'х', onShift: 'Х', keyCode: 'BracketLeft' },
  { letter: 'ъ', onShift: 'Ъ', keyCode: 'BracketRight' },
  { letter: ' \\', onShift: '/', keyCode: 'Backslash' },
  { letter: 'Del', onShift: 'Del', keyCode: 'Delete' },
  { letter: 'CapsLock', onShift: 'CapsLock', keyCode: 'CapsLock' },
  { letter: 'ф', onShift: 'Ф', keyCode: 'KeyA' },
  { letter: 'ы', onShift: 'Ы', keyCode: 'KeyS' },
  { letter: 'в', onShift: 'В', keyCode: 'KeyD' },
  { letter: 'а', onShift: 'А', keyCode: 'KeyF' },
  { letter: 'п', onShift: 'П', keyCode: 'KeyG' },
  { letter: 'р', onShift: 'Р', keyCode: 'KeyH' },
  { letter: 'о', onShift: 'О', keyCode: 'KeyJ' },
  { letter: 'л', onShift: 'Л', keyCode: 'KeyK' },
  { letter: 'д', onShift: 'Д', keyCode: 'KeyL' },
  { letter: 'ж', onShift: 'Ж', keyCode: 'Semicolon' },
  { letter: 'э', onShift: 'Э', keyCode: 'Quote' },
  { letter: 'Enter', onShift: 'Enter', keyCode: 'Enter' },
  { letter: 'Shift', onShift: 'Shift', keyCode: 'ShiftLeft' },
  { letter: 'я', onShift: 'Я', keyCode: 'KeyZ' },
  { letter: 'ч', onShift: 'Ч', keyCode: 'KeyX' },
  { letter: 'с', onShift: 'С', keyCode: 'KeyC' },
  { letter: 'м', onShift: 'М', keyCode: 'KeyV' },
  { letter: 'и', onShift: 'И', keyCode: 'KeyB' },
  { letter: 'т', onShift: 'Т', keyCode: 'KeyN' },
  { letter: 'ь', onShift: 'Ь', keyCode: 'KeyM' },
  { letter: 'б', onShift: 'Б', keyCode: 'Comma' },
  { letter: 'ю', onShift: 'Ю', keyCode: 'Period' },
  { letter: '/', onShift: ',', keyCode: 'Slash' },
  { letter: '↑', onShift: '↑', keyCode: 'ArrowUp' },
  { letter: 'Shift ', onShift: 'Shift', keyCode: 'ShiftRight' },
  { letter: 'Ctrl', onShift: 'Ctrl', keyCode: 'ControlLeft' },
  { letter: 'Win', onShift: 'Win', keyCode: 'MetaLeft' },
  { letter: 'Alt', onShift: 'Alt', keyCode: 'AltLeft' },
  { letter: '', onShift: '', keyCode: 'Space' },
  { letter: 'Alt', onShift: 'Alt', keyCode: 'AltRight' },
  { letter: '←', onShift: '←', keyCode: 'ArrowLeft' },
  { letter: '↓', onShift: '↓', keyCode: 'ArrowDown' },
  { letter: '→', onShift: '→', keyCode: 'ArrowRight' },
  { letter: 'Ctrl', onShift: 'Ctrl', keyCode: 'ControlRight' },
];

export default dataRu;
